initial product-config code. validation includes data types, min/max, regex and allowed values checks
stackabletech/product-config pull request #1
Opened 2021-01-29 09:39 UTC by maltesander

2021-04-18 19:32 UTC, lfrancke requested changes
I did not finish the review unfortunately, submitting anyway before my holiday.

The major change that I'd like to see is better documentation and better terminology.
During the review I got pretty confused about the different terms ProductConfig, ConfigItem, OptionName, OptionValue, ConfigSetting, ConfigOption...

2021-04-18 19:32 UTC, lfrancke commented on src/util.rs
> +    let product_version = Version::parse(version)?;
Parsing the version again, it might really make sense to parse once

2021-04-18 19:32 UTC, lfrancke commented on src/util.rs
> +/// Get the correct value from recommended / default values depending on the version
This does not help me understand what's going on

2021-04-18 19:32 UTC, lfrancke commented on src/util.rs
> +/// * `version` - product / controller version
I'm extremely confused by the terminology but I believe "controller version" is probably wrong?

2021-04-18 19:32 UTC, lfrancke commented on src/util.rs
> +            let from_version = Version::parse(from)?;
Can we parse this from JSON to `Version` immediately?
Because we're doing it over and over here

2021-04-18 19:32 UTC, lfrancke commented on src/validation.rs
> +//type ConfigValidatorResult<T> = std::result::Result<T, error::Error>;
leftover?

2021-04-19 08:20 UTC, maltesander commented on src/lib.rs
> +    Recommended(String),
Renamed it. You get the recommended value if the role matches and required is true. Or if a dependency is missing and the dependent option has a recommended value. I thought to introduce another enum member for RequiredDependency or sth. like this.

2021-04-19 08:25 UTC, maltesander commented on src/lib.rs
> +    Error(Error),
The errors contain the value for debugging purposes. Im not sure, with error you really should not use the value so i would not like to return it (like in case of warning). But im ok with returning it. It is a philosophy thing i would say.

2021-04-19 09:31 UTC, maltesander commented on src/lib.rs
> +pub struct ProductConfig {
Yes they are very similiar. ProductConfig is basically a processed ConfigItem/ConfigSpec.

2021-04-19 10:00 UTC, maltesander commented on src/util.rs
> +/// - provided role + required == true (if role is None is wildcard for add all)
We look for options in the JSON that match the provided kind, version and role and where the role is required.

2021-04-19 10:05 UTC, maltesander commented on src/util.rs
> +                if Some(config_option_role.name.as_str()) == role && config_option_role.required {
Yes. You only get back values that are required and have a recommended value. Ill change it, i think yours makes more sense.

2021-04-19 10:21 UTC, maltesander commented on src/util.rs
> +            let from_version = Version::parse(from)?;
You mean via serde? We would need to write our own deserializer.

2021-04-27 14:23 UTC, merged