Switch from json to yaml
stackabletech/product-config pull request #25
Opened 2021-06-30 07:17 UTC by razvan

2021-06-30 14:47 UTC, lfrancke requested changes

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +    /// Validates the given [merged_properties] by performing the following actions:
Do links to own arguments work?

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +                    if check_datatype.is_err() {
I believe a if let makes more sense here so you avoid the `err().unwrap()` later

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +                    // was provided by recommended value?
This is not a proper sentence. Something is off here (the second line mostly)

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +                    );
This seems complicated to me.

Why not do it differently:
- Iterate over each user-provided property and validate (i.e. iterate over `user_config` instead of over `self.config.properties` in `get_and_expand_properties`)
- Check if there are any values that are required that are missing
- Check if there are any values that are missing that have recommended defaults

This would mean changing/removing the `get_and_expand_properties` function I believe.

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +                    //if property.has_role_required(role) {
Why the commented out line? I don't really understand this case.

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +                            "".to_string(),
Should be a real explanation

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +                // override
As mentioned before: Not really an override but an unknown instead.

2021-06-30 14:47 UTC, lfrancke commented on src/lib.rs
> +            }
Again, maybe I totally misunderstand what's going on here but in the `name_from_kind` method you just pick the first one that matches the correct kind?

Isn't that...wrong?

2021-06-30 14:47 UTC, lfrancke commented on src/types.rs
> +    pub fn name_from_kind(&self, kind: &PropertyNameKind) -> Option<String> {
I've commented above but I don't understand what this method does. Or why.
Can you explain and/or add documentation?

2021-06-30 14:47 UTC, lfrancke commented on src/types.rs
> +/// This is a workaround to deserialize a String directly into a compiled regex.
I don't understand why we can't deserialize to Regex directly even with this comment.
Are you saying that something needs Eq, PartialOrd etc.?

Have you looked into using https://github.com/tailhook/serde-regex instead?

2021-06-30 14:47 UTC, lfrancke commented on src/validation.rs
> +/*
...

2021-06-30 14:47 UTC, lfrancke commented on src/validation.rs
> +        // // prepare "user" data
...

2021-06-30 14:47 UTC, lfrancke commented on src/validation.rs
> +        // // prepare "user" data
I did not look at this file past this point because it's very hard to see what' actually in use and what's not.

2021-06-30 14:47 UTC, lfrancke commented on src/writer.rs
> +/// Accepts HashMap<String, Option<String>> or BTreeMap<String, Option<String>>.
Should probably document what you're doing with empty values

2021-06-30 14:47 UTC, lfrancke commented on src/writer.rs
> +                writer.write(&k, "\"\"")?;
I'm not convinced this is correct but let's leave it in here for now.

2021-06-30 18:20 UTC, maltesander commented on src/lib.rs
> +        let product_version = semver_parse(version).unwrap();
We can not use "?" since the method returns no result. 

For now the version comes directly from the operators and the custom resource (which therefore should be fine as long as we stick to the enums). 

If we ever change that (away from the enums towards ranges what we kinda discussed at some point) we should definitely have a result here. I will add it for now.

What do you think? This is important since it is the only interface we have.

2021-06-30 18:23 UTC, maltesander commented on src/types.rs
> +        Ok(semver_parse(&self.as_of_version)? <= *product_version)
Yes we can write a deserializer for as_of_version and the version to/from range in the default or recommended values.

2021-06-30 18:30 UTC, maltesander commented on src/util.rs
> +pub(crate) fn expand_properties(
Added some documentation, i think we clarified the other parts, so i resolve it.

2021-06-30 18:31 UTC, maltesander commented on src/lib.rs
> +    /// Validates the given [merged_properties] by performing the following actions:
I dont quite understand? Can you elaborate?

2021-06-30 19:12 UTC, maltesander commented on src/lib.rs
> +            }
Yes but it (should) be unique. You will only have one Env / Cli kind and multiple Files (with different names though)

2021-06-30 19:20 UTC, maltesander commented on src/writer.rs
> +                writer.write(&k, "\"\"")?;
We had a discussion where we basically need to support:
key="value"
key=""
key=
key
...
This requires us (unrelated to the writer) to work with <String, Option<String>> all the time.

2021-06-30 19:27 UTC, maltesander commented on src/types.rs
> +/// This is a workaround to deserialize a String directly into a compiled regex.
Not sure why it didnt work. Will try.

2021-07-01 08:06 UTC, maltesander commented on src/lib.rs
> +                    );
Decided to keep as it is.

2021-07-01 08:09 UTC, maltesander commented on src/types.rs
> +/// This is a workaround to deserialize a String directly into a compiled regex.
Serde-regex does not implement Eq/PartialOrd/JsonSchema etc which we need later on to generate crds. So we stay with our own implementation.

2021-07-01 10:27 UTC, lfrancke approved these changes, later dismissed
One comment left, up to you whether you want to change it or not

2021-07-01 10:27 UTC, lfrancke commented on src/lib.rs
> +                            name.to_string(),
nitpick but the name is already in the nested error
This should be something along the lines of `The property NAME is required but missing`

2021-07-01 10:37 UTC, maltesander commented on src/lib.rs
> +                            name.to_string(),
The property name is there, its the value that is missing?

2021-07-01 10:56 UTC, lfrancke approved these changes

2021-07-01 10:58 UTC, merged